spring:
  application:
    name: running-app  # ???? ??

  # ?????? ?? (??: H2 ?????? ?? ?)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # ??? ?? ? DB ??? ?? ??
    show-sql: true     # ???? SQL? ??? ??

# ??? ?? ?? JWT ??
jwt:
  secret: ${JWT_SECRET} # .env ?? ?????? ???
  expiration-time: 86400000 # 24?? (ms ??)