spring:
  profiles:
    active: local

  # DB
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    # DB 구조는 Flyway로 관리. JPA는 검증만 하도록 설정 변경
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  flyway:
    validate-on-migrate: false        # 파일 수정 허용
    clean-on-validation-error: true   # 에러 발생시 DB 새로 생성
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 86400000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL에 들어가는 파라미터 값 확인
